version: "3.7"

services:

  client:
    build:
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
